import numpy

ITERATIONS = 1000
MOTOR_FORCE = 25
GRAVITY = -9.8
LOOP_DELAY = 1.0/60.0

SIN_START = 0
SIN_END = 2 * numpy.pi

BACK_LEG_AMPLITUDE = numpy.pi/4
BACK_LEG_FREQUENCY = 25
BACK_LEG_PHASE_OFFSET = 0

NUMBER_OF_GENERATIONS = 50
POPULATION_SIZE = 20
